spring.application.name=portfolio-api

spring.datasource.url=${DB_URL}

spring.flyway.enabled=true

logging.level.org.springframework.security=DEBUG

server.servlet.context-path=/api/v1

spring.profiles.active=dev

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}
cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api.key=${CLOUDINARY_API_KEY}
cloudinary.api.secret=${CLOUDINARY_API_SECRET}
