spring.application.name=portfolio-api

spring.datasource.url=${DB_URL}

spring.flyway.enabled=true

logging.level.org.springframework.security=DEBUG

server.servlet.context-path=/api/v1

spring.profiles.active=dev
